<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Device.Hosting</RootNamespace>
    <AssemblyName>Device.Hosting</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Device.Client\Device.Client.csproj" />
    <ProjectReference Include="..\Device.Contracts\Device.Contracts.csproj" />
    <ProjectReference Include="..\Device.Server\Device.Server.csproj" />
    <ProjectReference Include="..\Device.Simulators\Device.Simulators.csproj" />
    <ProjectReference Include="..\Device.Drivers.Udl\Device.Drivers.Udl.csproj" />
    <ProjectReference Include="..\Device.Drivers.Samples\Device.Drivers.Samples.csproj" />
  </ItemGroup>
</Project>
