<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Device.Server</RootNamespace>
    <AssemblyName>Device.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Device.Contracts\Device.Contracts.csproj" />
  </ItemGroup>
</Project>
