<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Device.Simulators</RootNamespace>
    <AssemblyName>Device.Simulators</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Device.Contracts\Device.Contracts.csproj" />
    <ProjectReference Include="..\Device.Server\Device.Server.csproj" />
    <ProjectReference Include="..\Device.Client\Device.Client.csproj" />
  </ItemGroup>
</Project>
